const fluxogramaComp = [
  {
    id: 0,
    title: "Cálculo Diferencial e Integral I",
    status: "done",
    periodoSugerido: 1,
    creditos: 5,
  },
  {
    id: 1,
    title: "Cálculo Diferencial e Integral II",
    status: "done",
    periodoSugerido: 2,
    creditos: 5,
  },
  {
    id: 2,
    title: "Introdução à Programação",
    status: "done",
    periodoSugerido: 1,
    creditos: 4,
  },
  {
    id: 3,
    title: "Introdução à Álgebra Linear",
    status: "done",
    periodoSugerido: 2,
    creditos: 3,
  },
  {
    id: 4,
    title: "Introdução à Geometria Analítica",
    status: "done",
    periodoSugerido: 1,
    creditos: 3,
  },
  {
    id: 5,
    title: "Química dos Materiais",
    status: "not-started",
    periodoSugerido: 1,
    creditos: 5,
  },
  {
    id: 6,
    title: "Física I",
    status: "done",
    periodoSugerido: 2,
    creditos: 6,
  },
  {
    id: 7,
    title: "Física II",
    status: "in-progress",
    periodoSugerido: 3,
    creditos: 6,
  },
  {
    id: 8,
    title: "Modelagem Computacional",
    status: "done",
    periodoSugerido: 2,
    creditos: 2,
  },
  {
    id: 9,
    title: "Desenho Técnico I",
    status: "done",
    periodoSugerido: 2,
    creditos: 2,
  },
  {
    id: 10,
    title: "Ética Profissional e Humanidades",
    status: "done",
    periodoSugerido: 2,
    creditos: 2,
  },
  {
    id: 11,
    title: "Ciências do Ambiente",
    status: "done",
    periodoSugerido: 1,
    creditos: 2,
  },
  {
    id: 12,
    title: "Cálculo Numérico",
    status: "in-progress",
    periodoSugerido: 3,
    creditos: 4,
  },
  {
    id: 13,
    title: "Cálculo Vetorial",
    status: "not-started",
    periodoSugerido: 3,
    creditos: 5,
  },
  {
    id: 14,
    title: "Algoritmos e Estruturas de Dados",
    status: "in-progress",
    periodoSugerido: 3,
    creditos: 4,
    tests: [
      {
        id: 0,
        title: "Teste 1",
        status: "done",
        grade: 8.5,
        date: "2020-09-01",
      },
      {
        id: 1,
        title: "Teste 2",
        status: "not-started",
        grade: 7.5,
        date: "2020-10-01",
      },
    ],
  },
  {
    id: 15,
    title: "Probabilidade e Estatística",
    status: "done",
    periodoSugerido: 3,
    creditos: 4,
  },
  {
    id: 16,
    title: "Introdução a Equações Diferenciais",
    status: "done",
    periodoSugerido: 4,
    creditos: 4,
  },
  {
    id: 17,
    title: "Física III",
    status: "not-started",
    periodoSugerido: 4,
    creditos: 5,
  },
  {
    id: 18,
    title: "Métodos Numéricos de Otimização",
    status: "not-started",
    periodoSugerido: 4,
    creditos: 4,
  },
  {
    id: 19,
    title: "Matemática Discreta I",
    status: "not-started",
    periodoSugerido: 4,
    creditos: 5,
  },
  {
    id: 20,
    title: "Estudos de Casos Empresariais",
    status: "not-started",
    periodoSugerido: 4,
    creditos: 3,
  },
  {
    id: 21,
    title: "Engenharia Econômica",
    status: "not-started",
    periodoSugerido: 4,
    creditos: 2,
  },
  {
    id: 22,
    title: "Introdução à Análise Real",
    status: "not-started",
    periodoSugerido: 5,
    creditos: 4,
  },
  {
    id: 23,
    title: "Métodos Numéricos para Equações Diferenciais",
    status: "not-started",
    periodoSugerido: 5,
    creditos: 4,
  },
  {
    id: 24,
    title: "Matemática Discreta II",
    status: "not-started",
    periodoSugerido: 5,
    creditos: 5,
  },
  {
    id: 25,
    title: "Sistemas Operacionais",
    status: "not-started",
    periodoSugerido: 5,
    creditos: 5,
  },
  {
    id: 26,
    title: "Sistema de Banco de Dados",
    status: "not-started",
    periodoSugerido: 5,
    creditos: 5,
  },
  {
    id: 27,
    title: "Análise do R",
    status: "not-started",
    periodoSugerido: 6,
    creditos: 4,
  },
  {
    id: 28,
    title: "Modelos Lineares",
    status: "not-started",
    periodoSugerido: 6,
    creditos: 4,
  },
  {
    id: 29,
    title: "Introdução à Redes e Comunicação de Dados",
    status: "done",
    periodoSugerido: 6,
    creditos: 4,
  },
  {
    id: 30,
    title: "Conceitos de Linguagens de Programação",
    status: "done",
    periodoSugerido: 6,
    creditos: 4,
  },
  {
    id: 31,
    title: "Eletiva I",
    status: "done",
    periodoSugerido: 6,
  },
  {
    id: 32,
    title: "Principios de Engenharia de Software",
    status: "not-started",
    periodoSugerido: 6,
    creditos: 4,
  },
  {
    id: 33,
    title: "Equações Diferenciais I",
    status: "not-started",
    periodoSugerido: 7,
    creditos: 4,
  },
  {
    id: 34,
    title: "Circuitos Lógicos",
    status: "not-started",
    periodoSugerido: 7,
    creditos: 4,
  },
  {
    id: 35,
    title: "Projeto e Análise de Algoritmos",
    status: "not-started",
    periodoSugerido: 7,
    creditos: 4,
  },
  {
    id: 36,
    title: "Eletiva II",
    status: "in-progress",
    periodoSugerido: 7,
  },
  {
    id: 37,
    title: "Introdução à Automação e Controle",
    status: "in-progress",
    periodoSugerido: 7,
    creditos: 3,
  },
  {
    id: 38,
    title: "Equações Diferenciais II",
    status: "not-started",
    periodoSugerido: 8,
    creditos: 4,
  },
  {
    id: 39,
    title: "Arquitetura de Computadores",
    status: "not-started",
    periodoSugerido: 8,
    creditos: 4,
  },
  {
    id: 40,
    title: "Linguagens Formais e Autômatos",
    status: "not-started",
    periodoSugerido: 8,
    creditos: 3,
  },
  {
    id: 41,
    title: "Processos Estocásticos",
    status: "not-started",
    periodoSugerido: 8,
    creditos: 4,
  },
  {
    id: 42,
    title: "Eletiva III",
    status: "not-started",
    periodoSugerido: 8,
  },
  {
    id: 43,
    title: "Estágio Supervisionado",
    status: "in-progress",
    periodoSugerido: 9,
    creditos: 6,
  },
  {
    id: 44,
    title: "Álgebra Linear Numérica",
    status: "not-started",
    periodoSugerido: 9,
    creditos: 4,
  },
  {
    id: 45,
    title: "Computabilidade",
    status: "not-started",
    periodoSugerido: 9,
    creditos: 3,
  },
  {
    id: 46,
    title: "Eletiva IV",
    status: "not-started",
    periodoSugerido: 9,
  },
  {
    id: 47,
    title: "Eletiva V",
    status: "not-started",
    periodoSugerido: 9,
  },
  {
    id: 48,
    title: "Modelagem e Controle de Sistemas",
    status: "not-started",
    periodoSugerido: 9,
    creditos: 4,
  },
  {
    id: 49,
    title: "Projeto de Graduação",
    status: "not-started",
    periodoSugerido: 10,
    creditos: 2,
  },
  {
    id: 50,
    title: "Métodos Númericos para Equações Diferenciais II",
    status: "not-started",
    periodoSugerido: 10,
    creditos: 5,
  },
  {
    id: 51,
    title: "Instrumentação e Experimentação",
    status: "not-started",
    periodoSugerido: 10,
    creditos: 3,
  },
  {
    id: 52,
    title: "Eletiva VI",
    status: "not-started",
    periodoSugerido: 10,
  },
];

module.exports = fluxogramaComp;
